### ISSUE TITLE
Version 0.2.0 target

### ISSUE THREAD

**Issue by lRomul** [Fonbet/argus-tensor-stream#2]
## TODO

- Postprocessing improvements:
(all these operations can be used via pytorch but it requires additional tensors to store data otherwise using CUDA it can be done without any memory/performance overheads)
    - [x] Normalization to [0, 1].
    - [x] Dimension order: `c h w`, `h w c`.
    - [x] More color spaces: greyscale, YCbCr (4:2:0, 4:2:2, 4:4:4 subsampling), HSV.
    - [x] Different image interpolation algorithms: nearest (default now), bilinear, bicubic, area.

- [x] Multi GPUs support, select cuda device of output tensor ('cuda:0', 'cuda:1').

- Frame rate options:
    - [x] Read at native frame rate like `-re` ffmpeg parameter (default now)
    - [x] Read as fast as possible 
    - [x] Read frame by frame without skipping (only files)

- [x] Read multiple videos at the same time.
(creating several processes with different input videos to work in parallel)

- Currently there are some restrictions that can be added as parameters at initialization: 
    - [x] Maximum 5 consumers can work with one video simultaneously.
    - [x] Buffer with frames stores 10 frames, so using delay option only last 10 frames can be obtained.
